import Video from 'components/Video/Video';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextJS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Video />
      </main>
    </div>
  );
};

export default Home;
