import Video from 'components/Video/Video';
import type { NextPage } from 'next';
import Head from 'next/head';
import * as S from './style';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextJS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <S.Main>
        <Video />
        <S.Title>
          AVATAR 2: O CAMINHO DA ÁGUA SURPREENDE OU DECEPCIONA? VEJA O QUE
          ACHAMOS! | Veredito
        </S.Title>
        <S.Description>
          Chegou a hora de saber o nosso VEREDITO de AVATAR 2: O CAMINHO DA
          ÁGUA! Depois de muitos anos, o segundo filme da franquia dirigida por
          James Cameron chega aos cinemas e nós trazemos aqui as nossas opiniões
          sobre o longa. Deixe o seu comentário no vídeo, curta, siga o canal e
          compartilhe o link com os seus amigos. Vamos nessa!
        </S.Description>
      </S.Main>
    </div>
  );
};

export default Home;
